---
services:
  webdav:
    build: .
    container_name: nginx-webdav
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - WEBDAV_USERNAME=webdavuser
      - WEBDAV_PASSWORD=securepassword
      - WEBDAV_UID=1000
      - WEBDAV_GID=1000
    volumes:
      - ./webdav:/var/www/webdav